#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Architecture.View.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/_AdminLayout.cshtml")]
    public partial class _Views__AdminLayout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views__AdminLayout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\_AdminLayout.cshtml"
   
    Layout = "";

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=UTF-8\"");

WriteLiteral(">\r\n    <!-- Meta, title, CSS, favicons, etc. -->\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(">\r\n\r\n    <title>");

            
            #line 13 "..\..\Views\_AdminLayout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" | </title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 399), Tuple.Create("\"", 446)
, Tuple.Create(Tuple.Create("", 406), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/css/bootstrap.min.css")
, 406), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 478), Tuple.Create("\"", 528)
, Tuple.Create(Tuple.Create("", 485), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/css/font-awesome.min.css")
, 485), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 560), Tuple.Create("\"", 603)
, Tuple.Create(Tuple.Create("", 567), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/css/nprogress.css")
, 567), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 635), Tuple.Create("\"", 696)
, Tuple.Create(Tuple.Create("", 642), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/css/jquery.mCustomScrollbar.min.css")
, 642), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 728), Tuple.Create("\"", 772)
, Tuple.Create(Tuple.Create("", 735), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/css/custom.min.css")
, 735), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n\r\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Views\_AdminLayout.cshtml"
Write(RenderSection("css", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"");

WriteLiteral("></script>\r\n\r\n</head>\r\n\r\n<body");

WriteLiteral(" class=\"nav-md\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container body\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"main_container\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"col-md-3 left_col menu_fixed\"");

WriteLiteral(" >\r\n                <div");

WriteLiteral(" class=\"left_col scroll-view\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"navbar nav_title\"");

WriteLiteral(" style=\"border: 0;\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"/Home/Index\"");

WriteLiteral(" class=\"site_title\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-bars\"");

WriteLiteral("></i> <span>");

            
            #line 33 "..\..\Views\_AdminLayout.cshtml"
                                                                                             Write(ViewBag.CompanyContract.CompanyName);

            
            #line default
            #line hidden
WriteLiteral("!</span></a>\r\n                    </div>\r\n\r\n                    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n\r\n                    <!-- menu profile quick info -->\r\n                " +
"    <div");

WriteLiteral(" class=\"profile clearfix\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"profile_pic\"");

WriteLiteral(">\r\n                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1636), Tuple.Create("\"", 1675)
, Tuple.Create(Tuple.Create("", 1642), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/images/img.jpg")
, 1642), false)
);

WriteLiteral(" alt=\"...\"");

WriteLiteral(" class=\"img-circle profile_img\"");

WriteLiteral(">\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"profile_info\"");

WriteLiteral(@">
                            <span>Hoşgeldiniz,</span>
                            <h2>John Doe</h2>
                        </div>
                    </div>
                    <!-- /menu profile quick info -->

                    <br />
                    
");

WriteLiteral("                    ");

            
            #line 52 "..\..\Views\_AdminLayout.cshtml"
               Write(MvcHtmlString.Create(@ViewBag.Html.ToString()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                     \r\n                    <!-- /sidebar menu -->\r\n            " +
"        <!-- /menu footer buttons -->\r\n                    <div");

WriteLiteral(" class=\"sidebar-footer hidden-small\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" data-placement=\"top\"");

WriteLiteral(" title=\"Settings\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"glyphicon glyphicon-cog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                        </a>\r\n                        <a");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" data-placement=\"top\"");

WriteLiteral(" title=\"FullScreen\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"glyphicon glyphicon-fullscreen\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                        </a>\r\n                        <a");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" data-placement=\"top\"");

WriteLiteral(" title=\"Lock\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"glyphicon glyphicon-eye-close\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                        </a>\r\n                        <a");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" data-placement=\"top\"");

WriteLiteral(" title=\"Logout\"");

WriteLiteral(" href=\"login.html\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"glyphicon glyphicon-off\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                        </a>\r\n                    </div>\r\n             " +
"       <!-- /menu footer buttons -->\r\n                </div>\r\n            </div>" +
"\r\n\r\n            <!-- top navigation -->\r\n            <div");

WriteLiteral(" class=\"top_nav\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"nav_menu\"");

WriteLiteral(">\r\n                    <nav>\r\n                        <div");

WriteLiteral(" class=\"nav toggle\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" id=\"menu_toggle\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-bars\"");

WriteLiteral("></i></a>\r\n                        </div>\r\n\r\n                        <ul");

WriteLiteral(" class=\"nav navbar-nav navbar-right\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"user-profile dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3918), Tuple.Create("\"", 3957)
, Tuple.Create(Tuple.Create("", 3924), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/images/img.jpg")
, 3924), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(">John Doe\r\n                                    <span");

WriteLiteral(" class=\" fa fa-angle-down\"");

WriteLiteral("></span>\r\n                                </a>\r\n                                <" +
"ul");

WriteLiteral(" class=\"dropdown-menu dropdown-usermenu pull-right\"");

WriteLiteral(">\r\n                                    <li><a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral("> Profile</a></li>\r\n                                    <li>\r\n                   " +
"                     <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"badge bg-red pull-right\"");

WriteLiteral(">50%</span>\r\n                                            <span>Settings</span>\r\n " +
"                                       </a>\r\n                                   " +
" </li>\r\n                                    <li><a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(">Help</a></li>\r\n                                    <li><a");

WriteLiteral(" href=\"login.html\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-sign-out pull-right\"");

WriteLiteral("></i> Log Out</a></li>\r\n                                </ul>\r\n                  " +
"          </li>\r\n\r\n                            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"dropdown-toggle info-number\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-envelope-o\"");

WriteLiteral("></i>\r\n                                    <span");

WriteLiteral(" class=\"badge bg-green\"");

WriteLiteral(">6</span>\r\n                                </a>\r\n                                " +
"<ul");

WriteLiteral(" id=\"menu1\"");

WriteLiteral(" class=\"dropdown-menu list-unstyled msg_list\"");

WriteLiteral(" role=\"menu\"");

WriteLiteral(">\r\n                                    <li>\r\n                                    " +
"    <a>\r\n                                            <span");

WriteLiteral(" class=\"image\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 5547), Tuple.Create("\"", 5586)
, Tuple.Create(Tuple.Create("", 5553), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/images/img.jpg")
, 5553), false)
);

WriteLiteral(" alt=\"Profile Image\"");

WriteLiteral(" /></span>\r\n                                            <span>\r\n                 " +
"                               <span>John Smith</span>\r\n                        " +
"                        <span");

WriteLiteral(" class=\"time\"");

WriteLiteral(">3 mins ago</span>\r\n                                            </span>\r\n        " +
"                                    <span");

WriteLiteral(" class=\"message\"");

WriteLiteral(@">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a>
                                            <span");

WriteLiteral(" class=\"image\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 6378), Tuple.Create("\"", 6417)
, Tuple.Create(Tuple.Create("", 6384), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/images/img.jpg")
, 6384), false)
);

WriteLiteral(" alt=\"Profile Image\"");

WriteLiteral(" /></span>\r\n                                            <span>\r\n                 " +
"                               <span>John Smith</span>\r\n                        " +
"                        <span");

WriteLiteral(" class=\"time\"");

WriteLiteral(">3 mins ago</span>\r\n                                            </span>\r\n        " +
"                                    <span");

WriteLiteral(" class=\"message\"");

WriteLiteral(@">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a>
                                            <span");

WriteLiteral(" class=\"image\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 7209), Tuple.Create("\"", 7248)
, Tuple.Create(Tuple.Create("", 7215), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/images/img.jpg")
, 7215), false)
);

WriteLiteral(" alt=\"Profile Image\"");

WriteLiteral(" /></span>\r\n                                            <span>\r\n                 " +
"                               <span>John Smith</span>\r\n                        " +
"                        <span");

WriteLiteral(" class=\"time\"");

WriteLiteral(">3 mins ago</span>\r\n                                            </span>\r\n        " +
"                                    <span");

WriteLiteral(" class=\"message\"");

WriteLiteral(@">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a>
                                            <span");

WriteLiteral(" class=\"image\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 8040), Tuple.Create("\"", 8079)
, Tuple.Create(Tuple.Create("", 8046), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/images/img.jpg")
, 8046), false)
);

WriteLiteral(" alt=\"Profile Image\"");

WriteLiteral(" /></span>\r\n                                            <span>\r\n                 " +
"                               <span>John Smith</span>\r\n                        " +
"                        <span");

WriteLiteral(" class=\"time\"");

WriteLiteral(">3 mins ago</span>\r\n                                            </span>\r\n        " +
"                                    <span");

WriteLiteral(" class=\"message\"");

WriteLiteral(@">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <div");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                            <a>\r\n                             " +
"                   <strong>See All Alerts</strong>\r\n                            " +
"                    <i");

WriteLiteral(" class=\"fa fa-angle-right\"");

WriteLiteral(@"></i>
                                            </a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>

            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div");

WriteLiteral(" class=\"right_col\"");

WriteLiteral(" role=\"main\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12 col-sm-12 col-xs-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"x_panel\"");

WriteLiteral(">\r\n                  <div");

WriteLiteral(" class=\"x_title\"");

WriteLiteral(">\r\n                    <h2>");

            
            #line 176 "..\..\Views\_AdminLayout.cshtml"
                   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                    <ul");

WriteLiteral(" class=\"nav navbar-right panel_toolbox\"");

WriteLiteral(">\r\n                      <li><a");

WriteLiteral(" class=\"collapse-link\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-up\"");

WriteLiteral("></i></a>\r\n                      </li>\r\n                      <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-wrench\"");

WriteLiteral("></i></a>\r\n                        <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(" role=\"menu\"");

WriteLiteral(">\r\n                          <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Settings 1</a>\r\n                          </li>\r\n                          <li><" +
"a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Settings 2</a>\r\n                          </li>\r\n                        </ul>\r\n" +
"                      </li>\r\n                      <li><a");

WriteLiteral(" class=\"close-link\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-close\"");

WriteLiteral("></i></a>\r\n                      </li>\r\n                    </ul>\r\n              " +
"      <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n                  </div>\r\n                  <div");

WriteLiteral(" class=\"x_content\"");

WriteLiteral(" id=\"mainContent\"");

WriteLiteral(">\r\n");

WriteLiteral("                      ");

            
            #line 195 "..\..\Views\_AdminLayout.cshtml"
                 Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n                  </div>\r\n                </div>\r\n              </div>\r\n       " +
"     </div>\r\n            <!-- /page content -->\r\n            <!-- footer content" +
" -->\r\n            <footer>\r\n                <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n                    Gentelella - Bootstrap Admin Template by <a");

WriteLiteral(" href=\"https://colorlib.com\"");

WriteLiteral(">Colorlib</a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n            </footer>\r\n            <!-- /footer content -->\r\n        </d" +
"iv>\r\n    </div>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11168), Tuple.Create("\"", 11209)
, Tuple.Create(Tuple.Create("", 11174), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/jquery.min.js")
, 11174), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11233), Tuple.Create("\"", 11277)
, Tuple.Create(Tuple.Create("", 11239), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/bootstrap.min.js")
, 11239), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11301), Tuple.Create("\"", 11341)
, Tuple.Create(Tuple.Create("", 11307), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/fastclick.js")
, 11307), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11365), Tuple.Create("\"", 11405)
, Tuple.Create(Tuple.Create("", 11371), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/nprogress.js")
, 11371), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11429), Tuple.Create("\"", 11494)
, Tuple.Create(Tuple.Create("", 11435), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/jquery.mCustomScrollbar.concat.min.js")
, 11435), false)
);

WriteLiteral("></script>    \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11522), Tuple.Create("\"", 11563)
, Tuple.Create(Tuple.Create("", 11528), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/custom.min.js")
, 11528), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 217 "..\..\Views\_AdminLayout.cshtml"
Write(RenderSection("script", false));

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
