#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Architecture.View.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/_BrowseLayout.cshtml")]
    public partial class _Views__BrowseLayout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views__BrowseLayout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\_BrowseLayout.cshtml"
  
    Layout = "~/Views/_AdminLayout.cshtml";
    WebGrid grid = new WebGrid(canPage:false);
    grid.Bind(ViewBag.DataSource);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <title>");

            
            #line 12 "..\..\Views\_BrowseLayout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET Application</title>\r\n");

DefineSection("css", () => {

            
            #line 13 "..\..\Views\_BrowseLayout.cshtml"
    
            
            #line default
            #line hidden
WriteLiteral("\r\n    <!-- Datatables -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 396), Tuple.Create("\"", 454)
, Tuple.Create(Tuple.Create("", 403), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/css/dataTables.bootstrap.min.css")
, 403), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 486), Tuple.Create("\"", 541)
, Tuple.Create(Tuple.Create("", 493), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/css/buttons.bootstrap.min.css")
, 493), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 573), Tuple.Create("\"", 632)
, Tuple.Create(Tuple.Create("", 580), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/css/fixedHeader.bootstrap.min.css")
, 580), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 664), Tuple.Create("\"", 722)
, Tuple.Create(Tuple.Create("", 671), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/css/responsive.bootstrap.min.css")
, 671), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 754), Tuple.Create("\"", 810)
, Tuple.Create(Tuple.Create("", 761), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/css/scroller.bootstrap.min.css")
, 761), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    ");

});

WriteLiteral("</head>\r\n<body>\r\n    \r\n    <div");

WriteLiteral(" class=\"x_content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"btn-toolbar editor\"");

WriteLiteral(" data-role=\"editor-toolbar\"");

WriteLiteral(" data-target=\"#editor-one\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(">Large Button</button>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(">Large Button</button>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(">Large Button</button>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(">Large Button</button>\r\n");

WriteLiteral("            ");

            
            #line 31 "..\..\Views\_BrowseLayout.cshtml"
       Write(Html.ActionLink("Kaydet","SaveExecute","Home",null,new { @class = "btn btn-success"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n         </div>\r\n            <div");

WriteLiteral(" class=\"well\"");

WriteLiteral(" style=\"overflow:auto;\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"btn btn-app\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i> Edit\r\n                </a>\r\n                <a");

WriteLiteral(" class=\"btn btn-app\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i> Edit\r\n                </a>\r\n                <a");

WriteLiteral(" class=\"btn btn-app\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i> Edit\r\n                </a>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

WriteLiteral("            ");

            
            #line 46 "..\..\Views\_BrowseLayout.cshtml"
       Write(grid.GetHtml(
             htmlAttributes: new { @id = "datatable-buttons", @class = "table table-striped table-bordered" },
           columns: ViewBag.Columns,
           caption: "Sonuç Listesi"
          
        ));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    \r\n");

WriteLiteral("    ");

            
            #line 54 "..\..\Views\_BrowseLayout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("script", () => {

            
            #line 56 "..\..\Views\_BrowseLayout.cshtml"
    
            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2215), Tuple.Create("\"", 2267)
, Tuple.Create(Tuple.Create("", 2221), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/jquery.dataTables.min.js")
, 2221), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2291), Tuple.Create("\"", 2347)
, Tuple.Create(Tuple.Create("", 2297), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/dataTables.responsive.min.js")
, 2297), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2371), Tuple.Create("\"", 2425)
, Tuple.Create(Tuple.Create("", 2377), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/dataTables.scroller.min.js")
, 2377), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2449), Tuple.Create("\"", 2504)
, Tuple.Create(Tuple.Create("", 2455), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/dataTables.bootstrap.min.js")
, 2455), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2528), Tuple.Create("\"", 2581)
, Tuple.Create(Tuple.Create("", 2534), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/dataTables.buttons.min.js")
, 2534), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2605), Tuple.Create("\"", 2662)
, Tuple.Create(Tuple.Create("", 2611), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/dataTables.fixedHeader.min.js")
, 2611), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2686), Tuple.Create("\"", 2740)
, Tuple.Create(Tuple.Create("", 2692), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/dataTables.keyTable.min.js")
, 2692), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2764), Tuple.Create("\"", 2808)
, Tuple.Create(Tuple.Create("", 2770), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/buttons.print.js")
, 2770), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2832), Tuple.Create("\"", 2880)
, Tuple.Create(Tuple.Create("", 2838), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/buttons.html5.min.js")
, 2838), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2904), Tuple.Create("\"", 2952)
, Tuple.Create(Tuple.Create("", 2910), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/buttons.flash.min.js")
, 2910), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2976), Tuple.Create("\"", 3028)
, Tuple.Create(Tuple.Create("", 2982), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/buttons.bootstrap.min.js")
, 2982), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3052), Tuple.Create("\"", 3103)
, Tuple.Create(Tuple.Create("", 3058), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/responsive.bootstrap.js")
, 3058), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3127), Tuple.Create("\"", 3169)
, Tuple.Create(Tuple.Create("", 3133), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/pdfmake.min.js")
, 3133), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3193), Tuple.Create("\"", 3233)
, Tuple.Create(Tuple.Create("", 3199), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/vfs_fonts.js")
, 3199), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3257), Tuple.Create("\"", 3297)
, Tuple.Create(Tuple.Create("", 3263), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template/js/jszip.min.js")
, 3263), false)
);

WriteLiteral("></script>\r\n    ");

});

WriteLiteral("</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
