#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Architecture.View.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/_BrowseLayout2.cshtml")]
    public partial class _Views__BrowseLayout2_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views__BrowseLayout2_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\_BrowseLayout2.cshtml"
   
    Layout = "~/Views/_AdminLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 9 "..\..\Views\_BrowseLayout2.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n");

DefineSection("css", () => {

            
            #line 10 "..\..\Views\_BrowseLayout2.cshtml"
    
            
            #line default
            #line hidden
WriteLiteral("\r\n    <!-- favicon\r\n      ============================================ -->\r\n    <" +
"link");

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" href=\"img/favicon.ico\"");

WriteLiteral(">\r\n    <!-- Google Fonts\r\n        ============================================ --" +
">\r\n    <link");

WriteLiteral(" href=\"https://fonts.googleapis.com/css?family=Play:400,700\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <!-- Bootstrap CSS\r\n        ============================================ -" +
"->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 628), Tuple.Create("\"", 676)
, Tuple.Create(Tuple.Create("", 635), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/bootstrap.min.css")
, 635), false)
);

WriteLiteral(">\r\n    <!-- Bootstrap CSS\r\n        ============================================ -" +
"->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 788), Tuple.Create("\"", 839)
, Tuple.Create(Tuple.Create("", 795), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/font-awesome.min.css")
, 795), false)
);

WriteLiteral(">\r\n    <!-- owl.carousel CSS\r\n        ===========================================" +
"= -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 954), Tuple.Create("\"", 1001)
, Tuple.Create(Tuple.Create("", 961), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/owl.carousel.css")
, 961), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1031), Tuple.Create("\"", 1075)
, Tuple.Create(Tuple.Create("", 1038), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/owl.theme.css")
, 1038), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1105), Tuple.Create("\"", 1155)
, Tuple.Create(Tuple.Create("", 1112), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/owl.transitions.css")
, 1112), false)
);

WriteLiteral(">\r\n    <!-- animate CSS\r\n        ============================================ -->" +
"\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1265), Tuple.Create("\"", 1307)
, Tuple.Create(Tuple.Create("", 1272), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/animate.css")
, 1272), false)
);

WriteLiteral(">\r\n    <!-- normalize CSS\r\n        ============================================ -" +
"->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1419), Tuple.Create("\"", 1463)
, Tuple.Create(Tuple.Create("", 1426), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/normalize.css")
, 1426), false)
);

WriteLiteral(">\r\n    <!-- meanmenu icon CSS\r\n        ==========================================" +
"== -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1579), Tuple.Create("\"", 1626)
, Tuple.Create(Tuple.Create("", 1586), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/meanmenu.min.css")
, 1586), false)
);

WriteLiteral(">\r\n    <!-- main CSS\r\n        ============================================ -->\r\n " +
"   <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1733), Tuple.Create("\"", 1772)
, Tuple.Create(Tuple.Create("", 1740), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/main.css")
, 1740), false)
);

WriteLiteral(">\r\n    <!-- morrisjs CSS\r\n        ============================================ --" +
">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1883), Tuple.Create("\"", 1924)
, Tuple.Create(Tuple.Create("", 1890), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/morris.css")
, 1890), false)
);

WriteLiteral(">\r\n    <!-- mCustomScrollbar CSS\r\n        =======================================" +
"===== -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2043), Tuple.Create("\"", 2105)
, Tuple.Create(Tuple.Create("", 2050), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/jquery.mCustomScrollbar.min.css")
, 2050), false)
);

WriteLiteral(">\r\n    <!-- metisMenu CSS\r\n        ============================================ -" +
"->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2217), Tuple.Create("\"", 2265)
, Tuple.Create(Tuple.Create("", 2224), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/metisMenu.min.css")
, 2224), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2295), Tuple.Create("\"", 2348)
, Tuple.Create(Tuple.Create("", 2302), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/metisMenu-vertical.css")
, 2302), false)
);

WriteLiteral(">\r\n    <!-- calendar CSS\r\n        ============================================ --" +
">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2459), Tuple.Create("\"", 2510)
, Tuple.Create(Tuple.Create("", 2466), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/fullcalendar.min.css")
, 2466), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2540), Tuple.Create("\"", 2597)
, Tuple.Create(Tuple.Create("", 2547), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/fullcalendar.print.min.css")
, 2547), false)
);

WriteLiteral(">\r\n    <!-- x-editor CSS\r\n        ============================================ --" +
">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2708), Tuple.Create("\"", 2757)
, Tuple.Create(Tuple.Create("", 2715), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/editor/select2.css")
, 2715), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2787), Tuple.Create("\"", 2843)
, Tuple.Create(Tuple.Create("", 2794), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/editor/datetimepicker.css")
, 2794), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2873), Tuple.Create("\"", 2933)
, Tuple.Create(Tuple.Create("", 2880), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/editor/bootstrap-editable.css")
, 2880), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2963), Tuple.Create("\"", 3019)
, Tuple.Create(Tuple.Create("", 2970), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/editor/x-editor-style.css")
, 2970), false)
);

WriteLiteral(">\r\n    <!-- normalize CSS\r\n        ============================================ -" +
"->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3131), Tuple.Create("\"", 3181)
, Tuple.Create(Tuple.Create("", 3138), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/bootstrap-table.css")
, 3138), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3211), Tuple.Create("\"", 3264)
, Tuple.Create(Tuple.Create("", 3218), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/bootstrap-editable.css")
, 3218), false)
);

WriteLiteral(">\r\n    <!-- style CSS\r\n        ============================================ -->\r\n" +
"    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"style.css\"");

WriteLiteral(">\r\n    <!-- responsive CSS\r\n        ============================================ " +
"-->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3501), Tuple.Create("\"", 3546)
, Tuple.Create(Tuple.Create("", 3508), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/css/responsive.css")
, 3508), false)
);

WriteLiteral(">\r\n    <!-- modernizr JS\r\n        ============================================ --" +
">\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3642), Tuple.Create("\"", 3700)
, Tuple.Create(Tuple.Create("", 3648), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/vendor/modernizr-2.8.3.min.js")
, 3648), false)
);

WriteLiteral("></script>\r\n   ");

});

WriteLiteral("</head>\r\n<body>\r\n        <div");

WriteLiteral(" class=\"data-table-area mg-tb-15\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"sparkline13-list\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"sparkline13-hd\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"main-sparkline13-hd\"");

WriteLiteral(">\r\n                                    <h1>Products <span");

WriteLiteral(" class=\"table-project-n\"");

WriteLiteral(">Data</span> Table</h1>\r\n                                </div>\r\n                " +
"            </div>\r\n                            <div");

WriteLiteral(" class=\"sparkline13-graph\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"datatable-dashv1-list custom-datatable-overright\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" id=\"toolbar\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                            <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">Export Basic</option>\r\n                                            <option");

WriteLiteral(" value=\"all\"");

WriteLiteral(">Export All</option>\r\n                                            <option");

WriteLiteral(" value=\"selected\"");

WriteLiteral(">Export Selected</option>\r\n                                        </select>\r\n   " +
"                                 </div>\r\n                                    <ta" +
"ble");

WriteLiteral(" id=\"table\"");

WriteLiteral(" data-toggle=\"table\"");

WriteLiteral(" data-pagination=\"true\"");

WriteLiteral(" data-search=\"true\"");

WriteLiteral(" data-show-columns=\"true\"");

WriteLiteral(" data-show-pagination-switch=\"true\"");

WriteLiteral(" data-show-refresh=\"true\"");

WriteLiteral(" data-key-events=\"true\"");

WriteLiteral(" data-show-toggle=\"true\"");

WriteLiteral(" data-resizable=\"true\"");

WriteLiteral(" data-cookie=\"true\"");

WriteLiteral("\r\n                                           data-cookie-id-table=\"saveId\"");

WriteLiteral(" data-show-export=\"true\"");

WriteLiteral(" data-click-to-select=\"true\"");

WriteLiteral(" data-toolbar=\"#toolbar\"");

WriteLiteral(">\r\n                                        <thead>\r\n                             " +
"               <tr>\r\n                                                <th");

WriteLiteral(" data-field=\"state\"");

WriteLiteral(" data-checkbox=\"true\"");

WriteLiteral("></th>\r\n                                                <th");

WriteLiteral(" data-field=\"id\"");

WriteLiteral(">ID</th>\r\n                                                <th");

WriteLiteral(" data-field=\"name\"");

WriteLiteral(" data-editable=\"true\"");

WriteLiteral(">Product Title</th>\r\n                                                <th");

WriteLiteral(" data-field=\"company\"");

WriteLiteral(" data-editable=\"true\"");

WriteLiteral(">Stock</th>\r\n                                                <th");

WriteLiteral(" data-field=\"price\"");

WriteLiteral(" data-editable=\"true\"");

WriteLiteral(">Price</th>\r\n                                                <th");

WriteLiteral(" data-field=\"date\"");

WriteLiteral(" data-editable=\"true\"");

WriteLiteral(">Date</th>\r\n                                                <th");

WriteLiteral(" data-field=\"task\"");

WriteLiteral(" data-editable=\"true\"");

WriteLiteral(">Status</th>\r\n                                                <th");

WriteLiteral(" data-field=\"email\"");

WriteLiteral(" data-editable=\"true\"");

WriteLiteral(">Total Sales</th>\r\n                                                <th");

WriteLiteral(" data-field=\"action\"");

WriteLiteral(@">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td></td>
                                                <td>1</td>
                                                <td>Product Title</td>
                                                <td>Out Of Stock</td>
                                                <td>$54</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>2</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>3</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>4</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>5</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>6</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>7</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>8</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>9</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>10</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>11</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>12</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>13</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>14</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>15</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>16</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>17</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>18</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>19</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>20</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>21</td>
                                                <td>Product Title</td>
                                                <td>In Of Stock</td>
                                                <td>$5</td>
                                                <td>Jul 14, 2017</td>
                                                <td>Active</td>
                                                <td>$700</td>
                                                <td");

WriteLiteral(" class=\"datatable-ct\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral(@"></i>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
");

WriteLiteral("    ");

            
            #line 394 "..\..\Views\_BrowseLayout2.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("script", () => {

            
            #line 396 "..\..\Views\_BrowseLayout2.cshtml"
    
            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 24387), Tuple.Create("\"", 24436)
, Tuple.Create(Tuple.Create("", 24393), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/jquery-1.11.3.min.js")
, 24393), false)
);

WriteLiteral("></script>\r\n    <!-- bootstrap JS\r\n        ======================================" +
"====== -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 24541), Tuple.Create("\"", 24586)
, Tuple.Create(Tuple.Create("", 24547), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/bootstrap.min.js")
, 24547), false)
);

WriteLiteral("></script>\r\n    <!-- wow JS\r\n        ============================================" +
" -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 24685), Tuple.Create("\"", 24724)
, Tuple.Create(Tuple.Create("", 24691), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/wow.min.js")
, 24691), false)
);

WriteLiteral("></script>\r\n    <!-- price-slider JS\r\n        ===================================" +
"========= -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 24832), Tuple.Create("\"", 24883)
, Tuple.Create(Tuple.Create("", 24838), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/jquery-price-slider.js")
, 24838), false)
);

WriteLiteral("></script>\r\n    <!-- meanmenu JS\r\n        =======================================" +
"===== -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 24987), Tuple.Create("\"", 25034)
, Tuple.Create(Tuple.Create("", 24993), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/jquery.meanmenu.js")
, 24993), false)
);

WriteLiteral("></script>\r\n    <!-- owl.carousel JS\r\n        ===================================" +
"========= -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 25142), Tuple.Create("\"", 25190)
, Tuple.Create(Tuple.Create("", 25148), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/owl.carousel.min.js")
, 25148), false)
);

WriteLiteral("></script>\r\n    <!-- sticky JS\r\n        =========================================" +
"=== -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 25292), Tuple.Create("\"", 25337)
, Tuple.Create(Tuple.Create("", 25298), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/jquery.sticky.js")
, 25298), false)
);

WriteLiteral("></script>\r\n    <!-- scrollUp JS\r\n        =======================================" +
"===== -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 25441), Tuple.Create("\"", 25492)
, Tuple.Create(Tuple.Create("", 25447), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/jquery.scrollUp.min.js")
, 25447), false)
);

WriteLiteral("></script>\r\n    <!-- mCustomScrollbar JS\r\n        ===============================" +
"============= -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 25604), Tuple.Create("\"", 25670)
, Tuple.Create(Tuple.Create("", 25610), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/jquery.mCustomScrollbar.concat.min.js")
, 25610), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 25694), Tuple.Create("\"", 25749)
, Tuple.Create(Tuple.Create("", 25700), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/mCustomScrollbar-active.js")
, 25700), false)
);

WriteLiteral("></script>\r\n    <!-- metisMenu JS\r\n        ======================================" +
"====== -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 25854), Tuple.Create("\"", 25899)
, Tuple.Create(Tuple.Create("", 25860), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/metisMenu.min.js")
, 25860), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 25923), Tuple.Create("\"", 25971)
, Tuple.Create(Tuple.Create("", 25929), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/metisMenu-active.js")
, 25929), false)
);

WriteLiteral("></script>\r\n    <!-- data table JS\r\n        =====================================" +
"======= -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 26077), Tuple.Create("\"", 26124)
, Tuple.Create(Tuple.Create("", 26083), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/bootstrap-table.js")
, 26083), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 26148), Tuple.Create("\"", 26191)
, Tuple.Create(Tuple.Create("", 26154), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/tableExport.js")
, 26154), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 26215), Tuple.Create("\"", 26264)
, Tuple.Create(Tuple.Create("", 26221), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/data-table-active.js")
, 26221), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 26288), Tuple.Create("\"", 26344)
, Tuple.Create(Tuple.Create("", 26294), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/bootstrap-table-editable.js")
, 26294), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 26368), Tuple.Create("\"", 26418)
, Tuple.Create(Tuple.Create("", 26374), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/bootstrap-editable.js")
, 26374), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 26442), Tuple.Create("\"", 26499)
, Tuple.Create(Tuple.Create("", 26448), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/bootstrap-table-resizable.js")
, 26448), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 26523), Tuple.Create("\"", 26578)
, Tuple.Create(Tuple.Create("", 26529), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/colResizable-1.5.source.js")
, 26529), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 26602), Tuple.Create("\"", 26656)
, Tuple.Create(Tuple.Create("", 26608), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/bootstrap-table-export.js")
, 26608), false)
);

WriteLiteral("></script>\r\n    <!--  editable JS\r\n        ======================================" +
"====== -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 26761), Tuple.Create("\"", 26807)
, Tuple.Create(Tuple.Create("", 26767), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/jquery.mockjax.js")
, 26767), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 26831), Tuple.Create("\"", 26874)
, Tuple.Create(Tuple.Create("", 26837), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/mock-active.js")
, 26837), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 26898), Tuple.Create("\"", 26937)
, Tuple.Create(Tuple.Create("", 26904), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/select2.js")
, 26904), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 26961), Tuple.Create("\"", 27003)
, Tuple.Create(Tuple.Create("", 26967), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/moment.min.js")
, 26967), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 27027), Tuple.Create("\"", 27083)
, Tuple.Create(Tuple.Create("", 27033), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/bootstrap-datetimepicker.js")
, 27033), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 27107), Tuple.Create("\"", 27157)
, Tuple.Create(Tuple.Create("", 27113), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/bootstrap-editable.js")
, 27113), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 27181), Tuple.Create("\"", 27228)
, Tuple.Create(Tuple.Create("", 27187), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/xediable-active.js")
, 27187), false)
);

WriteLiteral("></script>\r\n    <!-- Chart JS\r\n        ==========================================" +
"== -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 27329), Tuple.Create("\"", 27377)
, Tuple.Create(Tuple.Create("", 27335), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/jquery.peity.min.js")
, 27335), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 27401), Tuple.Create("\"", 27445)
, Tuple.Create(Tuple.Create("", 27407), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/peity-active.js")
, 27407), false)
);

WriteLiteral("></script>\r\n    <!-- tab JS\r\n        ============================================" +
" -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 27544), Tuple.Create("\"", 27579)
, Tuple.Create(Tuple.Create("", 27550), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/tab.js")
, 27550), false)
);

WriteLiteral("></script>\r\n    <!-- plugins JS\r\n        ========================================" +
"==== -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 27682), Tuple.Create("\"", 27721)
, Tuple.Create(Tuple.Create("", 27688), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/plugins.js")
, 27688), false)
);

WriteLiteral("></script>\r\n    <!-- main JS\r\n        ===========================================" +
"= -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 27821), Tuple.Create("\"", 27857)
, Tuple.Create(Tuple.Create("", 27827), Tuple.Create<System.Object, System.Int32>(Href("~/Content/template2/js/main.js")
, 27827), false)
);

WriteLiteral("></script>\r\n    ");

});

WriteLiteral("</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
