//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecture.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class County
    {
        public short CountyId { get; set; }
        public string CountyName { get; set; }
        public Nullable<short> CityId { get; set; }
    
        public virtual City City { get; set; }
    }
}
