//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecture.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.EmployeeDetail = new HashSet<EmployeeDetail>();
        }
    
        public int DepartmentId { get; set; }
        public long CompanyId { get; set; }
        public long ManagerPotentialId { get; set; }
        public string DepartmentName { get; set; }
        public string UserName { get; set; }
        public string HostName { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public string UpdateUserName { get; set; }
        public Nullable<System.DateTime> UpdateSystemDate { get; set; }
        public string HostIp { get; set; }
        public string OperationKey { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeDetail> EmployeeDetail { get; set; }
    }
}
