//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecture.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int EmployeeDetailId { get; set; }
        public long PotentialId { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> SuperPotentialId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
