//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecture.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorCodes
    {
        public int ErrorCode { get; set; }
        public string ErrorDescription { get; set; }
        public byte Severity { get; set; }
        public string UserName { get; set; }
        public string HostName { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public Nullable<System.DateTime> UpdateUserName { get; set; }
        public Nullable<System.DateTime> UpdateSystemDate { get; set; }
        public string HosIp { get; set; }
    }
}
