//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecture.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Potential
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Potential()
        {
            this.PotentialContact = new HashSet<PotentialContact>();
            this.Authentication = new HashSet<Authentication>();
            this.CustomerDetail = new HashSet<CustomerDetail>();
            this.UserDetail = new HashSet<UserDetail>();
        }
    
        public long PotentialId { get; set; }
        public long CompanyId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Ssn { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public byte Status { get; set; }
        public byte PotentialType { get; set; }
        public byte PersonType { get; set; }
        public string UserName { get; set; }
        public string HostName { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public string UpdateUserName { get; set; }
        public Nullable<System.DateTime> UpdateSystemDate { get; set; }
        public string HostIp { get; set; }
        public string OperationKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PotentialContact> PotentialContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Authentication> Authentication { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDetail> CustomerDetail { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDetail> UserDetail { get; set; }
    }
}
