//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecture.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceAction
    {
        public int ResourceActionId { get; set; }
        public int ResourceId { get; set; }
        public Nullable<int> ActionId { get; set; }
        public string CommandName { get; set; }
        public string DisplayName { get; set; }
        public string Icon { get; set; }
        public Nullable<byte> ActionType { get; set; }
        public Nullable<byte> SortId { get; set; }
        public string Description { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
