//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecture.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource()
        {
            this.ResourceAction = new HashSet<ResourceAction>();
        }
    
        public int ResourceId { get; set; }
        public long CompanyId { get; set; }
        public string Code { get; set; }
        public string Text { get; set; }
        public string AssemblyName { get; set; }
        public string ControllerName { get; set; }
        public string ViewName { get; set; }
        public string Icon { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<byte> MenuType { get; set; }
        public Nullable<byte> SortId { get; set; }
        public Nullable<byte> ViewType { get; set; }
        public string Description { get; set; }
        public string UserName { get; set; }
        public string HostName { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public string UpdateUserName { get; set; }
        public Nullable<System.DateTime> UpdateSystemDate { get; set; }
        public string OperationKey { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceAction> ResourceAction { get; set; }
    }
}
