//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Types
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class dependent
    {
        public string essn { get; set; }
        public string dependent_name { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public string relationship { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
