//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Types
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {

        }

        public string fname { get; set; }
        public string minit { get; set; }
        public string lname { get; set; }
        public string ssn { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public string address { get; set; }
        public string sex { get; set; }
        public Nullable<int> salary { get; set; }
        public string superssn { get; set; }
        public Nullable<short> dno { get; set; }
        

    }
}
