//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Types
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class works_on
    {
        public string essn { get; set; }
        public short pno { get; set; }
        public Nullable<short> hours { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual project project { get; set; }
    }
}
